export default {
    
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',

    //university
    GET_UNIVERSITY_START:'GET_UNIVERSITY_START',
    GET_UNIVERSITY_SUCCESS: 'GET_UNIVERSITY_SUCCESS',
    GET_UNIVERSITY_FAILED: 'GET_UNIVERSITY_FAILED',

    //login

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    CHANGE_STATUS_ACTIVED: 'CHANGE_STATUS_ACTIVED',

    //Regiser: 
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    //Exam
    GET_ALL_EXAM_START: 'GET_ALL_EXAM_START',
    GET_ALL_EXAM_SUCCESS: 'GET_ALL_EXAM_SUCCESS',
    GET_ALL_EXAM_FAILED: 'GET_ALL_EXAM_FAILED',
    GET_EXAM_BY_ID_START: 'GET_EXAM_BY_ID_START',
    GET_EXAM_BY_ID_SUCCESS: 'GET_EXAM_BY_ID_SUCCESS',
    GET_EXAM_BY_ID_FAILED: 'GET_EXAM_BY_ID_FAILED',
    REGISTER_EXAM_SUCCESS: 'REGISTER_EXAM_SUCCESS',

    //Attendance

    GET_ATTENDANCE_BY_ID_EXAM_START: 'GET_ATTENDANCE_BY_ID_EXAM_START',
    GET_ATTENDANCE_BY_ID_EXAM_SUCCESS: 'GET_ATTENDANCE_BY_ID_EXAM_SUCCESS',
    GET_ATTENDANCE_BY_ID_EXAM_FAILED: 'GET_ATTENDANCE_BY_ID_EXAM_FAILED',

    // Userinfo
    CHANGE_USER_DATA:'CHANGE_USER_DATA'
}